name: chem-store_local

services:
  client:
    container_name: "chem-store_client_local"
    build:
      context: ./client
      dockerfile: Dockerfile_local
    expose:
      - 3000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./client:/app
      - /app/node_modules
  server:
    container_name: "chem-store_server_local"
    restart: always
    build:
      context: server
      dockerfile: Dockerfile_local
    user: 1000:1000
    expose:
      - 5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./server:/app
      - /app/node_modules
  nginx:
    image: nginx
    restart: "no"
    container_name: "chem-store_nginx_local"
    ports:
      - 7000:80
    depends_on:
      - server
      - client
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/local:/etc/nginx/conf.d
